services:

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: wikidb
      POSTGRES_USER: wikiuser
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
      
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://wikiuser:secret@db:5432/wikidb

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: